CREATE TABLE TAXI_REQUEST (
    REQ_ID                    INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ARRIVEATDESTINATIONTIME   VARCHAR(30),
    DEPARTFROMDESTINATIONTIME VARCHAR(30),
    PRICE                     DOUBLE,
    DEPARTFROMHOTELTIME       VARCHAR(30),
    ARRIVEATHOTELTIME         VARCHAR(30),
    DESTINATIONADRESS         VARCHAR(30),
    HOTELNAME                 VARCHAR(30),
    NUMBEROFTRAVELERS         INT );