CREATE TABLE LUNCH_RESERVATION (REC_ID
	INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        GUEST_NAME VARCHAR(80),
        ROOM_NUMBER INT,
        NUMBER_OF_LUNCHES INT,
        LUNCH_DATE DATE);