<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="lunchServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/lunchServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/lunchServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://j2ee.netbeans.org/wsdl/LunchService/LunchReservation">
    <import location="LunchReservation.wsdl" namespace="http://j2ee.netbeans.org/wsdl/LunchService/LunchReservation"/>
    <plnk:partnerLinkType name="lunchServiceLinkType">
        <plnk:role name="lunchServiceRole" portType="ns:lunchServicePortType"/>
    </plnk:partnerLinkType>
</definitions>

